// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trading.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    user_id
)
VALUES ($1)
RETURNING id, user_id, cash_balance, created_at, updated_at
`

func (q *Queries) CreateAccount(ctx context.Context, userID int64) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, userID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    account_id,
    symbol,
    side,
    quantity,
    execution_price,
    total_value,
    status
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, account_id, symbol, side, quantity, execution_price, total_value, status, created_at, updated_at
`

type CreateOrderParams struct {
	AccountID      int64          `json:"account_id"`
	Symbol         string         `json:"symbol"`
	Side           string         `json:"side"`
	Quantity       int32          `json:"quantity"`
	ExecutionPrice pgtype.Numeric `json:"execution_price"`
	TotalValue     pgtype.Numeric `json:"total_value"`
	Status         string         `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.AccountID,
		arg.Symbol,
		arg.Side,
		arg.Quantity,
		arg.ExecutionPrice,
		arg.TotalValue,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Symbol,
		&i.Side,
		&i.Quantity,
		&i.ExecutionPrice,
		&i.TotalValue,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (
    account_id,
    symbol,
    quantity,
    average_price
)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, symbol, quantity, average_price, created_at, updated_at
`

type CreatePositionParams struct {
	AccountID    int64          `json:"account_id"`
	Symbol       string         `json:"symbol"`
	Quantity     int32          `json:"quantity"`
	AveragePrice pgtype.Numeric `json:"average_price"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, createPosition,
		arg.AccountID,
		arg.Symbol,
		arg.Quantity,
		arg.AveragePrice,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Symbol,
		&i.Quantity,
		&i.AveragePrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUserID = `-- name: GetAccountByUserID :one
SELECT id, user_id, cash_balance, created_at, updated_at
FROM accounts 
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetAccountByUserID(ctx context.Context, userID int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUserID, userID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, account_id, symbol, side, quantity, execution_price, total_value, status, created_at, updated_at
FROM orders
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Symbol,
		&i.Side,
		&i.Quantity,
		&i.ExecutionPrice,
		&i.TotalValue,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrdersByAccountID = `-- name: GetOrdersByAccountID :many
SELECT id, account_id, symbol, side, quantity, execution_price, total_value, status, created_at, updated_at 
FROM orders
WHERE account_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOrdersByAccountID(ctx context.Context, accountID int64) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Symbol,
			&i.Side,
			&i.Quantity,
			&i.ExecutionPrice,
			&i.TotalValue,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPositionByAccountAndSymbol = `-- name: GetPositionByAccountAndSymbol :one
SELECT id, account_id, symbol, quantity, average_price, created_at, updated_at
FROM positions
WHERE
    account_id = $1
    AND symbol = $2
LIMIT 1
`

type GetPositionByAccountAndSymbolParams struct {
	AccountID int64  `json:"account_id"`
	Symbol    string `json:"symbol"`
}

func (q *Queries) GetPositionByAccountAndSymbol(ctx context.Context, arg GetPositionByAccountAndSymbolParams) (Position, error) {
	row := q.db.QueryRow(ctx, getPositionByAccountAndSymbol, arg.AccountID, arg.Symbol)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Symbol,
		&i.Quantity,
		&i.AveragePrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPositionsByAccountID = `-- name: GetPositionsByAccountID :many
SELECT id, account_id, symbol, quantity, average_price, created_at, updated_at 
FROM positions
WHERE account_id = $1
ORDER BY symbol
`

func (q *Queries) GetPositionsByAccountID(ctx context.Context, accountID int64) ([]Position, error) {
	rows, err := q.db.Query(ctx, getPositionsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Symbol,
			&i.Quantity,
			&i.AveragePrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders 
SET 
    execution_price = $2, 
    total_value = $3, 
    status = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, account_id, symbol, side, quantity, execution_price, total_value, status, created_at, updated_at
`

type UpdateOrderParams struct {
	ID             int64          `json:"id"`
	ExecutionPrice pgtype.Numeric `json:"execution_price"`
	TotalValue     pgtype.Numeric `json:"total_value"`
	Status         string         `json:"status"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrder,
		arg.ID,
		arg.ExecutionPrice,
		arg.TotalValue,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Symbol,
		&i.Side,
		&i.Quantity,
		&i.ExecutionPrice,
		&i.TotalValue,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE positions 
SET 
    quantity = $2, 
    average_price = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, account_id, symbol, quantity, average_price, created_at, updated_at
`

type UpdatePositionParams struct {
	ID           int64          `json:"id"`
	Quantity     int32          `json:"quantity"`
	AveragePrice pgtype.Numeric `json:"average_price"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, updatePosition, arg.ID, arg.Quantity, arg.AveragePrice)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Symbol,
		&i.Quantity,
		&i.AveragePrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
