// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watchlists.sql

package queries

import (
	"context"
)

const addWatchlistItem = `-- name: AddWatchlistItem :one
INSERT INTO watchlist_items (
    watchlist_id,
    symbol
)
VALUES ($1, $2)
RETURNING id, watchlist_id, symbol, created_at
`

type AddWatchlistItemParams struct {
	WatchlistID int64  `json:"watchlist_id"`
	Symbol      string `json:"symbol"`
}

func (q *Queries) AddWatchlistItem(ctx context.Context, arg AddWatchlistItemParams) (WatchlistItem, error) {
	row := q.db.QueryRow(ctx, addWatchlistItem, arg.WatchlistID, arg.Symbol)
	var i WatchlistItem
	err := row.Scan(
		&i.ID,
		&i.WatchlistID,
		&i.Symbol,
		&i.CreatedAt,
	)
	return i, err
}

const createWatchlist = `-- name: CreateWatchlist :one
INSERT INTO watchlists (
    user_id
)
VALUES ($1)
RETURNING id, user_id, created_at, updated_at
`

func (q *Queries) CreateWatchlist(ctx context.Context, userID int64) (Watchlist, error) {
	row := q.db.QueryRow(ctx, createWatchlist, userID)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWatchlistItem = `-- name: DeleteWatchlistItem :exec
DELETE FROM watchlist_items
WHERE id = $1
`

func (q *Queries) DeleteWatchlistItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteWatchlistItem, id)
	return err
}

const getWatchlistByUserID = `-- name: GetWatchlistByUserID :one
SELECT id, user_id, created_at, updated_at 
FROM watchlists 
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetWatchlistByUserID(ctx context.Context, userID int64) (Watchlist, error) {
	row := q.db.QueryRow(ctx, getWatchlistByUserID, userID)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWatchlistItems = `-- name: GetWatchlistItems :many
SELECT id, watchlist_id, symbol, created_at
FROM watchlist_items 
WHERE watchlist_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetWatchlistItems(ctx context.Context, watchlistID int64) ([]WatchlistItem, error) {
	rows, err := q.db.Query(ctx, getWatchlistItems, watchlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchlistItem{}
	for rows.Next() {
		var i WatchlistItem
		if err := rows.Scan(
			&i.ID,
			&i.WatchlistID,
			&i.Symbol,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
